utils:
  data_dir: /mnt/f/ngs_research/
  threads: 12
species:
  name: Oryza_sativa
  reference_genome: IRGSP-1.0
  biomart:
    biomart: plants_mart
    dataset: osativa_eg_gene
    host: https://plants.ensembl.org
project:
  # analyze genome expression
  genome_expression:
    name: genome_expression
    spr: SRP375151
    upper_gene: 20
